spring:
  redis:
    host: localhost
    port: 6379
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  application:
    name: microservice-eureka-user
logging:
  level:
    cn.cqcet.yidong1702.ch0301: debug
server:
  port: 7911
eureka:
  instance:
    hostname: microservice-eureka-user
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

