server:
  port: 7900
eureka:
  instance:
    prefer-ip-address: true
    hostname: microservice-euereka-order
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: microservice-euereka-order
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  redis:
    port: 6379
    host: localhost
  datasource:
    url: jdbc:mysql://localhost:3306/spring?useUnicode=true&characterEncoding=utf-8
    password: 123456
    username: root
    driver-class-name: com.mysql.jdbc.Driver